builds:
  - binary: ungitz
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: ungitz
    homepage: https://github.com/hrshankar2002/ungitz
    tap:
      owner: hrshankar2002
      name: homebrew-hrshankar2002
    commit_author:
      name: hrshankar2002
      email: hrshankar2002@gmail.com

checksum:
  name_template: 'checksums.txt'